CREATE TABLE GrupoDePersonas (
	Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Nombre NVARCHAR(MAX) NOT NULL
)


CREATE TABLE Persona(
	Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Nombre NVARCHAR(MAX) NOT NULL,
	Edad INT NOT NULL,
	IdGrupoDePersonas INT NOT NULL
)